<h3>Параметры</h3>
<table>
    <thead>
        <tr>
            <th>Ключ</th>
            <th>Значение</th>
            <th>Действие</th>
        </tr>
    </thead>    
<tbody>
<?php foreach ($this->params as $key => $val):?>
    <tr>
        <td><?php echo $this->escape($key); ?></td>
        <td><?php echo $this->escape($val); ?></td>        
        <td><a href="/params/clear/id/<?php echo $this->objectId;?>/key/<?php echo urlencode($key)?>">убрать</a></td>        
    </tr>    
<?php endforeach;?>
</tbody>        
</table>    

<?php echo $this->form; ?>