<?php echo $this->partial('calendar/elements/header_menu.phtml'); ?>
<?php echo $this->partial('calendar/elements/month_menu.phtml', array('data' => $this->date));?>

   
<div id="main_block">
    <div class="container">
        <div class="form">
            <?php if ($this->authError): ?>
                <div class="error">
                    <?php echo $this->authError; ?>
                </div>
            <?php endif;?>
            <h1>Войти в личный кабинет.</h1>
            <?php echo $this->form;?>
     
        </div>
    </div> 
</div>
      
<?php echo $this->partial('calendar/elements/footer.phtml',array(  
    'data' => $this->date,   
    'nextEvents' => $this->nextEvents,
    'prevEvents' => $this->prevEvents
)); ?>           
 
<?php echo $this->partial('calendar/elements/copyright.phtml');?>               
