<?php echo $this->partial('calendar/elements/header_menu.phtml'); ?>
<?php echo $this->partial('calendar/elements/month_menu.phtml', array('data' => $this->date));?>


<div id="main_block" class="clearfix">
    <div class="container">
        <div class="form">
            <h1>Регистрация на сайте.</h1>
            <?php echo $this->form;?>
        </div>
    </div>
</div>

<?php echo $this->partial('calendar/elements/footer.phtml',array(
    'data' => $this->date,
    'nextEvents' => $this->nextEvents,
    'prevEvents' => $this->prevEvents
)); ?>

<?php echo $this->partial('calendar/elements/copyright.phtml');?>
