<b>ПРАВИЛА ПРЕДОСТАВЛЕНИЯ ПОДПИСКИ НА КОНТЕНТ</b>
<p>
  Правила предоставления Подписки на Контент (далее по тексту «Правила») разработаны в соответствии с требованиями действующего законодательства Российской Федерации и регулируют отношения по предоставлению Контент-провайдером Абонентам Подписки на Контент.
</p>
<p>
  Настоящие Правила являются публичной офертой и могут быть приняты Абонентом не иначе как путем присоединения к ним в целом. Принять настоящие Правила Абонент может путем осуществления Заказа в порядке, предусмотренном разделом 4 настоящих Правил.
</p>
<p>
    <b>1. Определения</b><br/>
    <p>
        1.1. Абонент-абонент (физическое лицо, Корпоративный клиент), с которым Оператором заключен договор на предоставление услуг связи (далее по тексту «Договор») с выделением не менее одного Абонентского номера и/или Уникального кода идентификации
    </p>
    <p>
        1.2.  Абонентский номер -телефонный номер, выделяемый Абоненту в соответствии с Договором, с помощью которого производится идентификация Абонентского оборудования с установленной в нем SIM-картой.
    </p>
    <p>
        1.3. Абонентское оборудование-подключаемое к сети связи абонентское устройство (абонентская станция) – телефонный аппарат и т.п., - позволяющее передавать и/или принимать информацию, и/или комплектующие и аксессуары к нему.
    </p>
    <p>
        1.4. Заказ - действия Абонента, предусмотренные п. 4.1. настоящих Правил, осуществляемые с целью получения доступа к Подписке на Контент.
    </p>
    <p>
        1.5.Контент-провайдер:<br/>
        - ООО «ИнкорМедиа», ОГРН 1067757853228<br/>
        - ООО «Диджитал Онлайн», ОГРН 1117746454187<br/>
        - ООО «Ай-Куб», ОГРН 5087746430404<br/>
        - ООО «МосКомСвязь», ОГРН 1107746426875, 119146,
        Москва, Комсомольский проспект, д. 7, стр. 2<br/>
        - ООО «СМС СЕРВИСЫ», САНКТ-ПЕТЕРБУРГ УЛ. БОЛЬШАЯ ЗЕЛЕНИНА, Д.8, КОРП.2, ЛИТ.А<br/>
        - ЗАО «Контент – провайдер Первый Альтернативный», ОГРН 1057748030427<br/>
    </p>
    <p>
        1.6. Контентная услуга-дополнительная услуга Оператора, повышающая потребительскую ценность услуг связи, заключающаяся в предоставлении Оператором Абоненту доступа к Подписке на Контент.
    </p>
    <p>
        1.7. Корпоративный клиент - Абонент (юридическое лицо илииндивидуальный предприниматель), с которым Оператором заключен Договор с выделением не менее одного Абонентского номера и/или Уникального кода идентификации. Корпоративный клиент соглашается, что действия его работников, пользующихся Подпиской на Контент(далее по тексту «Пользователи»), считаются действиями Корпоративного клиента.
    </p>
    <p>
        1.8.Оператор:<br/>
        – Открытое акционерное общество «МобильныеТелеСистемы»
        (г. Москва, ул. Марксистская, д 4)<br/>
        – Открытое акционерное общество "Вымпелком"<br/>
        – Открытое акционерное общество "МегаФон"<br/>
        – Закрытое акционерное общество "Байкалвестком"<br/>
        оказывающее услуги связи на основании лицензий, являющееся стороной по Договору с Абонентом.
    </p>
    <p>
        1.9. Стоимость услуги - плата, взимаемая Оператором с Абонента за предоставление Контентной услуги.
    </p>
    <p>
        1.10.   Уникальный код идентификации -указанное в Договоре уникальное сочетание цифровых, буквенных и/или символьных обозначений, используемое для однозначной идентификации Абонентского оборудования в процессе оказания услуг связи.
    </p>
    <b>2. Описание Подписки на Контент</b><br/>
    <p>
        2.1. Контент-провайдер предоставляет Абоненту возможность получать информационные смс сообщения (по тексту «Контент»), содержащие названия православных праздников и событий  на текущий день (по тексту «Подписка на Контент»)
        <br/>
        В случае неполучения от Абонента отказа от Подписки на Контент, срок предоставления Подписки на Контент автоматически продлевается каждый раз на 1 день до момента самостоятельного отключения Абонентом Подписки на Контент.
    </p>
    <p> 2.2. Подписка на контент предусматривает ежедневную рассылку информационных сообщений </p>
    <p> 2.3. Подписка на Контент предоставляется Контент-провайдером. Контентная услуга предоставляется Оператором с использованием оборудования и ресурсов сети Оператора. Ответственность за своевременное и качественное предоставление Подписки на Контент несет Контент-провайдер.</p>
    <b>3. Условия предоставления</b>
    <p>3.1. Контент-провайдер предоставляет Абоненту Подписку на Контент в порядке, предусмотренном настоящими Правилами.</p>
    <p> 3.2. Принять настоящие Правила Абонент может путем совершения Заказа.
        Корпоративный клиент считается принявшим настоящие Правила в случае, если один из Пользователей совершает Заказ.</p>
    <p> 3.3. Получить Подписку на Контент могут Абоненты, обладающие дееспособностью и правоспособностью, необходимыми для осуществления Заказа в соответствии с требованиями действующего законодательства РФ.</p>
    <p> 3.4. Абонент, желающий получить Подписку на Контент, должен располагать оборудованием, необходимым для оформления Заказа, получения Контентной услуги и Подписки на Контент.</p>
    <p>3.5. Осуществляя Заказ, Абонент подтверждает свое согласие с настоящими Правилами, а также подтверждает факт выполнения всех требований, предъявляемых Правилами к Абоненту.</p>
    <p>3.6. Контент-провайдер несет полную ответственность за соответствие Контента действующему законодательству и нормативно-правовым актам Российской Федерации.</p>
    <b>4. Порядок заказа</b>
    <p>4.1. Для получения доступа к Подписке на Контент Абоненту необходимо совершить следующие последовательные действия:</p>
    <p>4.1.1.На web-сайте http://orthcalendar.ru/ Контент-провайдера:<br/>
        - ввести свой абонентский номер;<br/>
        - подтвердить свое ознакомление и согласие с настоящими Правилами;</br>
        - нажать кнопку «Продолжить». </br>
    <p>4.1.2. На web-странице Оператора:<br/>
        - ознакомиться с условиями и Порядком предоставления Контентной услуги;<br/>
        - ввести код активации, полученный в SMS-сообщении;<br/>
        - в случае согласия с условиями и Порядком предоставления Контентной услугинажать кнопку «Получить доступ».<br/>
    <p> 4.2.    После получения от Абонента Заказа Абоненту направляется два SMS-сообщения:</p>

    <table border="1"  id="table1">
    <tr>
        <td align="center"><b><span style="font-family: Tahoma">
        <font size="2" color="#0000FF">Оператор</font></span></b></td>
        <td align="center">
        <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
        <b><span style="font-family: Tahoma"><font size="2" color="#0000FF">
        Контент-провайдер</font></span></b></td>
        <td align="center">
        <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
        <b><span style="font-family: Tahoma"><font size="2" color="#0000FF">
        Короткий номер – SMS-сообщение</font></span></b></td>
    </tr>
    <tr>
        <td rowspan="6">
        <p align="center"><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">ОАО «МТС»</font></span></td>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">ООО «ИнкорМедиа»</font></span></td>
        <td><font color="#0000FF">
        <span style="line-height: 120%; font-family: Tahoma"><font size="2">- с
        номера МТС/MTSPodpiski/7887, содержащее информацию о факте подключения и
        условиях предоставления доступа к Подписке на </font></span>
        <font face="Tahoma" size="2">Контент</font><span style="line-height: 120%; font-family: Tahoma"><font size="2">,&nbsp;<br>
        - с номера 770785, содержащее код доступа к Контенту/ссылка на Контент.</font></span></font></td>
    </tr>
    <tr>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">ООО «СМС СЕРВИСЫ»</font></span></td>
        <td><font color="#0000FF"><font size="2" face="Tahoma">- с номера МТС/MTSPodpiski/7887,
        содержащее информацию о факте подключения и условиях предоставления
        доступа к Подписке на Контент,<br>
        - с номера 770640, содержащее код доступа</font><span style="line-height: 120%; font-family: Tahoma"><font size="2">
        к Контенту/ссылка на Контент.</font></span></font></td>
    </tr>
    <tr>
        <td><font color="#0000FF" size="2" face="Tahoma">ООО «Диджитал Онлайн»</font></td>
        <td><font color="#0000FF" size="2" face="Tahoma">- с номера МТС/MTSPodpiski/7887,
        содержащее информацию о факте подключения и условиях предоставления
        доступа к Подписке на Контент, <br>
        - с номера 770325, содержащее код доступа к Контенту/ссылка на Контент.</font></td>
    </tr>
    <tr>
        <td><font color="#0000FF" size="2" face="Tahoma">ООО «Ай-Куб»</font></td>
        <td><font color="#0000FF" size="2" face="Tahoma">- с номера МТС/MTSPodpiski/7887,
        содержащее информацию о факте подключения и условиях предоставления
        доступа к Подписке на Контент, <br>
        - с номера 770765, содержащее код доступа к Контенту/ссылка на Контент.</font></td>
    </tr>
    <tr>
        <td><font color="#0000FF">
        <span style="line-height: 120%; font-family: Tahoma"><font size="2">ООО
        «</font></span><font size="2"><span style="line-height: 115%; font-family: Tahoma">МосКомСвязь</span></font><span style="line-height: 120%; font-family: Tahoma"><font size="2">»</font></span></font></td>
        <td><font color="#0000FF"><font size="2" face="Tahoma">- с номера МТС/MTSPodpiski/7887,
        содержащее информацию о факте подключения и условиях предоставления
        доступа к Подписке на Контент,<br>
        - с номера </font><font size="2">
        <span style="line-height: 115%; font-family: Tahoma">771312</span><font face="Tahoma">,
        содержащее код доступа</font></font><span style="line-height: 120%; font-family: Tahoma"><font size="2">
        к Контенту/ссылка на Контент.</font></span></font></td>
    </tr>
    <tr>
        <td><font color="#0000FF">
        <span style="line-height: 120%; font-family: Tahoma"><font size="2">ЗАО
        «</font></span><font size="2"><span style="line-height: 115%; font-family: Tahoma">Контент – провайдер Первый Альтернативный</span></font><span style="line-height: 120%; font-family: Tahoma"><font size="2">»</font></span></font></td>
        <td><font color="#0000FF"><font size="2" face="Tahoma">- с номера МТС/MTSPodpiski/7887,
        содержащее информацию о факте подключения и условиях предоставления
        доступа к Подписке на Контент,<br>
        - с номера </font><font size="2">
        <span style="line-height: 115%; font-family: Tahoma">771053</span><font face="Tahoma">,
        содержащее код доступа</font></font><span style="line-height: 120%; font-family: Tahoma"><font size="2">
        к Контенту/ссылка на Контент.</font></span></font></td>
    </tr>
    <tr>
        <td rowspan="5">
        <p align="center"><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">ОАО «МегаФон»</font></span></td>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">ООО «Ай-Куб»</font></span></td>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">- с номера 5051/MegafonPro, содержащее
        информацию о факте подключения и условиях предоставления доступа к
        Подписке на Контент.</font></span></td>
    </tr>
    <tr>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">ООО «СМС СЕРВИСЫ»</font></span></td>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">- с номера 5051/MegafonPro, содержащее
        информацию о факте подключения и условиях предоставления доступа к
        Подписке на Контент.</font></span></td>
    </tr>
    <tr>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">ООО «ИнкорМедиа»</font></span></td>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">- с номера 5051/MegafonPro, содержащее
        информацию о факте подключения и условиях предоставления доступа к
        Подписке на Контент.</font></span></td>
    </tr>
    <tr>
        <td><font color="#0000FF">
        <span style="line-height: 120%; font-family: Tahoma"><font size="2">ООО
        «</font></span><font size="2"><span style="line-height: 115%; font-family: Tahoma">МосКомСвязь</span></font><span style="line-height: 120%; font-family: Tahoma"><font size="2">»</font></span></font></td>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">- с номера 5051/MegafonPro, содержащее
        информацию о факте подключения и условиях предоставления доступа к
        Подписке на Контент.</font></span></td>
    </tr>
    <tr>
        <td><font color="#0000FF">
        <span style="line-height: 120%; font-family: Tahoma"><font size="2">ЗАО
        «</font></span><font size="2"><span style="line-height: 115%; font-family: Tahoma">Контент – провайдер Первый Альтернативный</span></font><span style="line-height: 120%; font-family: Tahoma"><font size="2">»</font></span></font></td>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">- с номера 5051/MegafonPro, содержащее
        информацию о факте подключения и условиях предоставления доступа к
        Подписке на Контент.</font></span></td>
    </tr>
    <tr>
        <td align="center" rowspan="4">
        <span style="line-height: 115%; font-family: Tahoma">
        <font size="2" color="#0000FF">ОАО «ВымпелКом»</font></span></td>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">ООО «Диджитал Онлайн»</font></span></td>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">- с номера
        <span style="background-image: none; background-repeat: repeat; background-attachment: scroll; background-position: 0% 0%">
        910</span>1, содержащее информацию о факте подключения и условиях
        предоставления доступа к Подписке на Контент.</font></span></td>
    </tr>
    <tr>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">ООО «СМС СЕРВИСЫ»</font></span></td>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">- с номера 2210, содержащее информацию о
        факте подключения и условиях предоставления доступа к Подписке на
        Контент.</font></span></td>
    </tr>
    <tr>
        <td><font color="#0000FF">
        <span style="line-height: 120%; font-family: Tahoma"><font size="2">ООО
        «</font></span><font size="2"><span style="line-height: 115%; font-family: Tahoma">МосКомСвязь</span></font><span style="line-height: 120%; font-family: Tahoma"><font size="2">»</font></span></font></td>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">- с номера 2535, содержащее информацию о
        факте подключения и условиях предоставления доступа к Подписке на
        Контент.</font></span></td>
    </tr>
    <tr>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">ООО «Контент – провайдер Первый Альтернативный»</font></span></td>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">- с номера 7044, содержащее информацию о
        факте подключения и условиях предоставления доступа к Подписке на
        Контент.</font></span></td>
    </tr>
    <tr>
        <td align="center"><font size="2" color="#0000FF">
        <span style="font-family: Tahoma">З</span></font><span style="line-height: 115%; font-family: Tahoma"><font size="2" color="#0000FF">АО
        «Байкалвестком»</font></span></td>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">ООО «СМС СЕРВИСЫ»</font></span></td>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">- с номера 2210, содержащее информацию о
        факте подключения и условиях предоставления доступа к Подписке на
        Контент.</font></span></td>
    </tr>
</table>

    <p>4.3. Выполнение Абонентом указанных в п. 4.1. настоящих Правил действий означает согласие Абонента на получение Контентной услуги в соответствии с заявленными Оператором условиями, на получение выбранной Абонентом Подписки на Контент в соответствии с заявленными Контент-провайдером условиями, на передачу данных, идентифицирующих Абонента (в частности, номера мобильного телефона Абонента) третьим лицам, привлекаемым Контент-провайдером для оказания Подписки на Контент, а также на получение бесплатных SMS-сообщений, напоминающих Абоненту о содержании, стоимости, порядке отказа от предоставления Контентной услуги.</p>

    <b>5. Порядок отключения</b>
    <p>5.1. Отключить Подписку на Контент можно посредством отключения Контентной услуги, одностороннего отказа от ее получения.</p>
    <p>5.2. Отключение Контентной услуги осуществляется Абонентом самостоятельно:</p>
    <p>а) с помощью интерфейсов, определенных Оператором. Подробнее об интерфейсах для отказа от получения такой услуги можно узнать на сайте Оператора www.mts.ru в разделе «Услуги по коротким номерам», на портале «Мои подписки» http://moipodpiski.mts.ru, или позвонив по единому номеру 88002500890.</p>
    <p>б) при Отправке ussd-команды *152*2#вызов (сообщение бесплатно для Абонента).</p>
    <p>в) при отправке сообщения на МО-номер(сообщение бесплатно для Абонента):</p>
<table border="1"  id="table1">
    <tr>
        <td align="center"><b><span style="font-family: Tahoma">
        <font size="2" color="#0000FF">Оператор</font></span></b></td>
        <td align="center">
        <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
        <b><span style="font-family: Tahoma"><font size="2" color="#0000FF">
        Контент-провайдер</font></span></b></td>
        <td align="center">
        <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
        <b><span style="font-family: Tahoma"><font size="2" color="#0000FF">
        Короткий номер – SMS-сообщение</font></span></b></td>
    </tr>
    <tr>
        <td rowspan="6">
        <p align="center"><span style="line-height: 120%; font-family: Tahoma">
        <font color="#0000FF" size="2">ОАО «МТС»</font></span></td>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font color="#0000FF" size="2">ООО «ИнкорМедиа»</font></span></td>
        <td><font color="#0000FF" face="Tahoma" size="2">- при отправке
        бесплатного сообщения на 6-ти-значный МО-номер 770785 с командой СТОП (STOP,
        stop, стоп, Стоп и т.п.) происходит прекращение оказания всех Контентных
        услуг, при предоставлении которых используется 6-ти-значный МО-номер
        770785.</font></td>
    </tr>
    <tr>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font color="#0000FF" size="2">ООО «СМС СЕРВИСЫ»</font></span></td>
        <td><font color="#0000FF" face="Tahoma" size="2">- при отправке
        бесплатного сообщения на 6-ти-значный МО-номер 770640 с командой СТОП (STOP,
        stop, стоп, Стоп и т.п.) происходит прекращение оказания всех Контентных
        услуг, при предоставления которых используется 6-ти-значный МО-номер
        770640.</font></td>
    </tr>
    <tr>
        <td><font color="#0000FF" face="Tahoma" size="2">ООО «Диджитал Онлайн»</font></td>
        <td><font color="#0000FF" face="Tahoma" size="2">- при отправке
        бесплатного сообщения на 6-ти-значный МО-номер 77325 с командой СТОП (STOP,
        stop, стоп, Стоп и т.п.) происходит прекращение оказания всех Контентных
        услуг, при предоставлении которых используется 6-ти-значный МО-номер
        770325.</font></td>
    </tr>
    <tr>
        <td><font color="#0000FF" face="Tahoma" size="2">ООО «Ай-Куб»</font></td>
        <td><font color="#0000FF" face="Tahoma" size="2">- при отправке
        бесплатного сообщения на 6-ти-значный МО-номер 770765 с командой СТОП (STOP,
        stop, стоп, Стоп и т.п.) происходит прекращение оказания всех Контентных
        услуг, при предоставлении которых используется 6-ти-значный МО-номер
        770765.</font></td>
    </tr>
    <tr>
        <td><font color="#0000FF" size="2">
        <span style="line-height: 120%; font-family: Tahoma">ООО «</span><span style="line-height: 115%; font-family: Tahoma">МосКомСвязь</span><span style="line-height: 120%; font-family: Tahoma">»</span></font></td>
        <td><font color="#0000FF" size="2"><font face="Tahoma">- при отправке
        бесплатного сообщения на 6-ти-значный МО-номер </font>
        <span style="line-height: 115%; font-family: Tahoma">771312 </span>
        <font face="Tahoma">с командой СТОП (STOP, stop, стоп, Стоп и т.п.)
        происходит прекращение оказания всех Контентных услуг, при
        предоставлении которых используется 6-ти-значный МО-номер </font>
        <span style="line-height: 115%; font-family: Tahoma">771312</span><font face="Tahoma">.</font></font></td>
    </tr>
    <tr>
        <td><font color="#0000FF" size="2">
        <span style="line-height: 120%; font-family: Tahoma">ЗАО «</span><span style="line-height: 115%; font-family: Tahoma">Контент – провайдер Первый Альтернативный</span><span style="line-height: 120%; font-family: Tahoma">»</span></font></td>
        <td><font color="#0000FF" size="2"><font face="Tahoma">- при отправке
        бесплатного сообщения на 6-ти-значный МО-номер </font>
        <span style="line-height: 115%; font-family: Tahoma">771053 </span>
        <font face="Tahoma">с командой СТОП (STOP, stop, стоп, Стоп и т.п.)
        происходит прекращение оказания всех Контентных услуг, при
        предоставлении которых используется 6-ти-значный МО-номер </font>
        <span style="line-height: 115%; font-family: Tahoma">771053</span><font face="Tahoma">.</font></font></td>
    </tr>
    <tr>
        <td rowspan="5">
        <p align="center"><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">ОАО «МегаФон»</font></span></td>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">ООО «Ай-Куб»</font></span></td>
        <td><font color="#0000FF" face="Tahoma" size="2">- при отправке
        бесплатного сообщения на МО-номер 5051 с командой СТОП 2601
        происходит прекращение оказания Услуги.</font></td>
    </tr>
    <tr>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">ООО «СМС СЕРВИСЫ»</font></span></td>
        <td><font color="#0000FF" face="Tahoma" size="2">- при отправке
        бесплатного сообщения на МО-номер 5051 с командой СТОП 2601
        происходит прекращение оказания Услуги.</font></td>
    </tr>
    <tr>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">ООО «ИнкорМедиа»</font></span></td>
        <td><font color="#0000FF" face="Tahoma" size="2">- при отправке
        бесплатного сообщения на МО-номер 5051 с командой СТОП 2601
        происходит прекращение оказания Услуги.</font></td>
    </tr>
    <tr>
        <td><font color="#0000FF">
        <span style="line-height: 120%; font-family: Tahoma"><font size="2">ООО
        «</font></span><font size="2"><span style="line-height: 115%; font-family: Tahoma">МосКомСвязь</span></font><span style="line-height: 120%; font-family: Tahoma"><font size="2">»</font></span></font></td>
        <td><font color="#0000FF" face="Tahoma" size="2">- при отправке
        бесплатного сообщения на МО-номер 5051 с командой СТОП 2601
        происходит прекращение оказания Услуги.</font></td>
    </tr>
    <tr>
        <td><font color="#0000FF">
        <span style="line-height: 120%; font-family: Tahoma"><font size="2">ЗАО
        «</font></span><font size="2"><span style="line-height: 115%; font-family: Tahoma">Контент – провайдер Первый Альтернативный</span></font><span style="line-height: 120%; font-family: Tahoma"><font size="2">»</font></span></font></td>
        <td><font color="#0000FF" face="Tahoma" size="2">- при отправке
        бесплатного сообщения на МО-номер 5051 с командой СТОП 2601
        происходит прекращение оказания Услуги.</font></td>
    </tr>
    <tr>
        <td align="center" rowspan="4">
        <span style="line-height: 115%; font-family: Tahoma">
        <font size="2" color="#0000FF">ОАО «ВымпелКом»</font></span></td>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">ООО «Диджитал Онлайн»</font></span></td>
        <td><font color="#0000FF" face="Tahoma" size="2">- при отправке
        бесплатного сообщения на МО-номер </font><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">
        <span style="background-image: none; background-repeat: repeat; background-attachment: scroll; background-position: 0% 0%">
        910</span>1 </font></span><font face="Tahoma" size="2" color="#0000FF">
        с командой СТОП происходит прекращение оказания Услуги.</font></td>
    </tr>
    <tr>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">ООО «СМС СЕРВИСЫ»</font></span></td>
        <td><font color="#0000FF" face="Tahoma" size="2">- при отправке
        бесплатного сообщения на МО-номер </font><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">2210</font></span><font color="#0000FF" face="Tahoma" size="2">
        с командой СТОП происходит прекращение оказания Услуги.</font></td>
    </tr>
    <tr>
        <td><font color="#0000FF">
        <span style="line-height: 120%; font-family: Tahoma"><font size="2">ООО
        «</font></span><font size="2"><span style="line-height: 115%; font-family: Tahoma">МосКомСвязь</span></font><span style="line-height: 120%; font-family: Tahoma"><font size="2">»</font></span></font></td>
        <td><font color="#0000FF" face="Tahoma" size="2">- при отправке
        бесплатного сообщения на МО-номер </font>
        <span style="line-height: 115%; font-family: Tahoma">
        <font size="2" color="#0000FF">2535 </font></span>
        <font color="#0000FF" face="Tahoma" size="2">с командой СТОП происходит
        прекращение оказания Услуги.</font></td>
    </tr>
    <tr>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">ООО «Контент – провайдер Первый Альтернативный»</font></span></td>
        <td><font color="#0000FF" face="Tahoma" size="2">- при отправке
        бесплатного сообщения на МО-номер </font><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">7044</font></span><font color="#0000FF" face="Tahoma" size="2">
        с командой СТОП происходит прекращение оказания Услуги.</font></td>
    </tr>
    <tr>
        <td align="center"><font size="2" color="#0000FF">
        <span style="font-family: Tahoma">З</span></font><span style="line-height: 115%; font-family: Tahoma"><font size="2" color="#0000FF">АО
        «Байкалвестком»</font></span></td>
        <td><span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">ООО «СМС СЕРВИСЫ»</font></span></td>
        <td><font color="#0000FF" face="Tahoma" size="2">- при отправке
        бесплатного сообщения на МО-номер 2210 с командой СТОП
        происходит прекращение оказания Услуги.</font></td>
    </tr>
</table>

<p>г) На странице «Управления подпиской на Корнтент» http://orthcalendar.ru/, введя свой номер и нажав кнопку «Отписаться».</p>
<p>д) Связавшись со Службой Поддержки Контент-провайдера:<br/>
- ООО «ИнкорМедиа» по тел.: 8-800-5555-638 (круглосуточно), факс: 8-495-9823887, электронной почтой helpdesk@incoremedia.ru.<br/>
- ООО «СМС СЕРВИСЫ» по тел.: 8-800-2000-334 (круглосуточно), электронной почтой subs@planet3.ru<br/>
- ООО МосКомСвязь по тел.: 8-800-1005-410 (круглосуточно), электронной почтой abuse@moscomsvjaz.ru<br/>
- ООО «Диджитал Онлайн» по тел.: 8-800-5555-484 (круглосуточно), электронной почтой helpdesk@digital-o.ru.<br/>
- ООО «Ай-Куб» по тел.: 8-800-3333-455 (круглосуточно), факс: 8-495-2870072, электронной почтой helpdesk@i-cb.ru.<br/>
- ЗАО «Контент – провайдер Первый Альтернативный» по тел.: 8-800-1007-337 (круглосуточно), факс: 8-495-3631-427, электронной почтой info@alt1.ru.<br/>
</p>
<p>5.3. Односторонним отказом Абонента от получения Контентной услуги считается нахождение Абонента в блокировке более 30 календарных дней.</p>

<b>6. Стоимость и порядок оплаты</b>

<p>6.1. Стоимость услуги составляет:</p>
<table border="1"  id="table1">
    <tr>
        <td align="center"><b><span style="font-family: Tahoma">
        <font size="2" color="#0000FF">Оператор</font></span></b></td>
        <td align="center">
        <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
        <b><span style="font-family: Tahoma"><font size="2" color="#0000FF">
        Периодичность списания</font></span></b></td>
        <td align="center">
        <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
        <font color="#0000FF"><b><span style="font-family: Tahoma">Сумма (руб. с
        НДС)</span></b></font></td>
    </tr>
    <tr>
        <td align="left"><span style="line-height: 120%; font-family: Tahoma">
        <font color="#0000FF" size="2">ОАО «МТС»</font></span></td>
        <td><font size="2" face="Tahoma" color="#0000FF">1 день</font></td>
        <td><font face="Tahoma" color="#0000FF"><font size="2">20.00 / 20.32</font></font></td>
    </tr>
    <tr>
        <td rowspan="2" align="left">
        <span style="line-height: 120%; font-family: Tahoma">
        <font size="2" color="#0000FF">ОАО «МегаФон»</font></span></td>
    </tr>
    <tr>
        <td><font size="2" face="Tahoma" color="#0000FF">1 день</font></td>
        <td><span lang="en-us"><font size="2" face="Tahoma" color="#0000FF">
        20.00</font></span></td>
    </tr>
    <tr>
        <td align="left" rowspan="2">
        <span style="line-height: 115%; font-family: Tahoma">
        <font size="2" color="#0000FF">ОАО «ВымпелКом»</font></span></td>
    </tr>
    <tr>
        <td><font size="2" face="Tahoma" color="#0000FF">1 день</font></td>
        <td><span lang="en-us"><font size="2" face="Tahoma" color="#0000FF">
        20.00</font></span></td>
    </tr>
    <tr>
        <td align="left"><font size="2" color="#0000FF">
        <span style="font-family: Tahoma">З</span></font><span style="line-height: 115%; font-family: Tahoma"><font size="2" color="#0000FF">АО
        «Байкалвестком»</font></span></td>
        <td><font size="2" face="Tahoma" color="#0000FF">1 день</font></td>
        <td><span lang="en-us"><font size="2" face="Tahoma" color="#0000FF">
        30.00</font></span></td>
    </tr>
</table>

<p>6.2. С порядком списания Стоимости услуги можно ознакомиться на Сайте Оператора www.mts.ru в разделе «Услуги по коротким номерам», введя короткий номер или идентификатор услуги в строке поиска, а также позвонив по единому номеру 88002500890.</p>
<b>7. Ограничения</b>
<p>7.1. В случае если Абонентское оборудование Абонента не поддерживает формат, необходимый для воспроизведения или просмотра Контента, предоставление Подписки не Контентне гарантируется.</p>
<p>7.2. Абонент вправе использовать Контент только в личных целях и не использовать для распространения путем продажи или иного отчуждения Контента третьим лицам. Использование Абонентом Подписки на Контентв целях распространения Контента третьим лицам нарушает законодательство РФ об интеллектуальной собственности и влечет для Абонента предусмотренную законодательством ответственность. Контент-провайдер не несет ответственности за противоправные действия Абонента.</p>
<p>7.3. Принимая настоящие Правила, Абонент соглашается с вышеуказанными ограничениями при предоставлении Подписки на Контент.</p>
<p>7.4. В случае нежелания Абонента пользоваться Подпиской на Контентс ограничениями, указанными в настоящих Правилах, Абонент вправе отключить Подписку на Контентв порядке, указанном в разделе 5 настоящих Правил.</p>
<b>8. Прочие условия</b>
<p>8.1. В процессе предоставления Контент-провайдером Абоненту Подписки на Контент Оператор осуществляет соответствующее информирование Абонента об условиях предоставления Контентной услуги посредством отправки SMS-сообщений с номера МТС/MTSPodpiski/7887.</p>
<p>8.2. Прекращение предоставления Контентной услуги влечет прекращение предоставления Подписки на Контент.</p>
<p>8.3. В случае отказа Абонента от предоставления Контентной услуги предоставление Подписки на Контент производится только после повторного выполнения Абонентом Заказа.</p>

<p>Version 18.04.2013</p>
