<?php echo $this->partial('calendar/elements/header_menu.phtml'); ?>
<?php echo $this->partial('calendar/elements/month_menu.phtml', array('data' => $this->date));?>


<div id="main_block">
    <div class="container">
        <div id='sms_subscribe'>
            <div class="form">
                <form>
                    <div class="element">
                            <b>Номер телефона:</b>
                            <input type='text' class='tilte' name='phone'>
                    </div>
                    <div>
                        <input type='checkbox' id='agree'>
                        я согласен с Правилами предоставления Подписки на рассылку православных праздников

                    </div>

                </form>
            </div>
            <div class='right'>
                <iframe
                    scrolling="YES"
                    src="<?php echo $this->url(array(), 'smsrights'); ?>"></iframe>
            </div>
        </div>

    </div>

</div>

<?php echo $this->partial('calendar/elements/footer.phtml',array(
    'data' => $this->date,
    'nextEvents' => $this->nextEvents,
    'prevEvents' => $this->prevEvents
)); ?>

<?php echo $this->partial('calendar/elements/copyright.phtml');?>
