<?php echo $this->partial('calendar/elements/header_menu.phtml'); ?>
<?php
  echo $this->partial(
    'calendar/elements/month_menu.phtml',
    array('data' => $this->date)
  );
?>
 <div id="article_card" class="clearfix">
            <div class="container">
                <div id="img">

                </div>
                <div id="card" class="clearfix">
                    <h1>заголовок</h1>

                    <h2>Православный календарь</h2>


                    <div id="information">
                        инфа
                    </div>



                    <div>
                        Поделиться статьей:
                        <script type="text/javascript" src="//yandex.st/share/share.js" charset="utf-8"></script>
                        <div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="none" data-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir,lj,friendfeed,moikrug"></div>
                    </div>
                </div>
            </div>
        </div>


 <div id="main_block">
            <div class="container">
                <div id="main_content">
                    <div id="description" class="content">
                        <!-- google_ad_section_start -->
                        контент
                        <!-- google_ad_section_end -->
                    </div>
                    <div>
                        <?php echo $this->partial(
                                'calendar/elements/social_plugin.phtml',
                                array(
                                    'pageId'=> $this->id,
                                    'url' => $this->link,

                                )); ?>
                    </div>
                </div>

            <div id="add_content">


                <div id="articles">
                    <h4>Что еще можно прочесть по теме <strong>ываыв</strong>:</h4>





                </div>

                <?php echo $this->partial('calendar/elements/adSense.phtml'); ?>
            </div>
        </div>
        </div>

<?php echo $this->partial('calendar/elements/footer.phtml',array(
                            'data' => $this->date,
                            'nextEvents' => $this->nextEvents,
                            'prevEvents' => $this->prevEvents
                         ));
?>

<?php echo $this->partial('calendar/elements/copyright.phtml');?>


