<?php echo $this->partial('calendar/elements/header_menu.phtml'); ?>
<?php echo $this->partial('calendar/elements/month_menu.phtml',
                          array(
                              'data' => $this->date
                          ));
?>
<div id="article_card" class="clearfix">
  <div class="container">
    <div id="img">
      <?php if (!$image = $this->event->getImage('300','200')) {
        $image = $this->everyDay->getImage('300','200');
      } ?>
      <img src="<?php echo $image; ?>">
    </div>
    <div id="card" class="clearfix">
      <h1><?php echo $this->event->getTitle();?></h1>
      <h2>Православный календарь</h2>
      <?php if (
        $this->event->getId() != Config_Interface::get(
          'everyWeekFast', 'events'
        )
      ):?>
        <div id="information">
          <?php $datesOfEvent = SmartFunction::getDates($this->event->getSmartFunction(), $this->date->getY());
          ?>
          <?php echo $this->event->getTitle();
          ?>
          в <?php echo $this->date->getY() ?> году
          <?php echo $this->toBe($this->event, $this->date, $datesOfEvent);?>
          <a href="/orthodoxy/<?=current($datesOfEvent) ?>">
            <?=SmartFunction::toString($datesOfEvent);?>
          </a>
        </div>
      <?php endif;?>
      <div>
        <?php
          $todo = $this->event->getToDo();
          echo empty($todo) ? '' : ('В этот день: '.implode(', ', $todo))
        ?>
      </div>
      <div>
        Поделиться статьей:
        <script
          type="text/javascript"
          src="//yandex.st/share/share.js"
          charset="utf-8">
        </script>
        <div
          class="yashare-auto-init"
          data-yashareL10n="ru"
          data-yashareType="none"
          data-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir,lj,friendfeed,moikrug">
        </div>
      </div>
    </div>
  </div>
</div>

<div id="main_block">
  <div class="container">
    <div id="main_content">
      <div id="description" class="content">
        <!-- google_ad_section_start -->
        <?php echo $this->event->getContent(array("\n" => '</p><p>')); ?>
        <?php if ($this->icons): ?>

        <?php $count = 0;?>
        <div id="icons" class='clearfix'>
          <h4>"<?php echo $this->event->getTitle();?>". Иконы.</h4>
          <?php foreach ($this->icons as $icon): ?>
            <?php if ($count >0 && $count % 6 == 0): ?>
              </div>
              <div id='icons' class='clearfix'>
            <?php endif;?>
            <div class='icon'>
              <a
                href='http://img.sancta.ru/crop/450x600/<?php echo $icon->image;?>'
                rel="lightbox[icons]"
                title='<?php echo $icon->text->annonce;?>'
              >
                <img
                  src='http://img.sancta.ru/crop/15x200/<?php echo $icon->image;?>'
                  title='<?php echo $icon->text->title;?>'
                  alt='<?php echo $icon->text->annonce;?>'
                >
              </a>
            </div>
            <?php $count++;?>
          <?php endforeach;?>
        </div>
      <?php endif;?>
        <!-- google_ad_section_end -->
      </div>
      <div>
        <?php echo $this->partial(
          'calendar/elements/social_plugin.phtml',
          array(
            'pageId'=> $this->event->getId(),
            'url' => $this->event->getLink(),
          )
        );?>
      </div>
    </div>
    <div id="add_content">

      <?php if (
        $this->event->getId() != Config_Interface::get(
          'everyWeekFast', 'events'
        )
      ):?>
      <div id="event_in_future">
      <h4>
        <strong>
          <?php echo $this->event->getTitle();?>
        </strong> в будущем году
      </h4>
      <div id="dates">
        <?php echo $this->EventInFuture($this->event, $this->date);?>
      </div>
    </div>
  <?php endif;?>
  <?php if ($this->articles->getCount() || $this->icons): ?>
    <div id="articles">
    <h4>
      Что еще можно прочесть по теме
      <strong>"<?php echo $this->event->getTitle();?>"</strong>:
    </h4>
    <?php if ($this->icons): ?>
      <p>
        <a href='
          <?php
            echo $this->url(
              array('event_name' => $this->event->getUrl()), 'eventicons'
            )
          ?>'>
          <?php echo $this->event->getTitle();?>. Иконы
        </a>
      </p>
    <?php endif;?>
    <?php foreach ($this->articles as $article): ?>
      <p>
        <?php echo $article->getLink($article->getTitle(), array(
        'event_id' => $this->event->getId()
        ));?>
      </p>
    <?php endforeach;?>
  </div>
  <?php endif; ?>
  <?php echo $this->partial('calendar/elements/adSense.phtml'); ?>
  </div>
  </div>
  </div>
<?php echo $this->partial('calendar/elements/footer.phtml',array(
  'data' => $this->date,
  'nextEvents' => $this->nextEvents,
  'prevEvents' => $this->prevEvents
));
?>
<?php echo $this->partial('calendar/elements/copyright.phtml');?>
<script>
    $("#to_future_show").click(function () {
       if ($("#otherDates").is(":hidden")) {
           $("#otherDates").show("slow");
       } else {
           $("#otherDates").hide("slow");
       }
    });
</script>
