<?php echo $this->partial('calendar/elements/header_menu.phtml'); ?>
<?php echo $this->partial('calendar/elements/month_menu.phtml',
                          array(
                              'data' => $this->date
                          ));
?>
 <div id="article_card" class="clearfix">
            <div class="container">
                <div id="img">
                    <?php  if (!$image = $this->event->getImage('300','200')) {
                       $image = $this->everyDay->getImage('300','200');
                    } ?>
                    <img src="<?php echo $image; ?>">
                </div>
                <div id="card" class="clearfix">
                    <h1><?php echo $this->event->getTitle();?></h1>

                    <h2>Православный календарь</h2>

                    <?php if ($this->event->getId() !=  Config_Interface::get('everyWeekFast', 'events')):?>
                    <div id="information">
                        <?php $datesOfEvent = SmartFunction::getDates($this->event->getSmartFunction(), $this->date->getY());?>
                        <?php echo $this->event->getTitle();?>
                        в <?php echo $this->date->getY() ?> году
                        <?php echo $this->toBe($this->event, $this->date, $datesOfEvent);?>
                        <a href="/orthodoxy/<?=current($datesOfEvent) ?>"><?=SmartFunction::toString($datesOfEvent);?></a>
                    </div>
                      <?php endif;?>
                   
                    <div>
                        <?php
                          $todo = $this->event->getToDo();
                          echo empty($todo) ? '' : ('В этот день: '.implode(', ', $todo))
                        ?>                        
                    </div>
                    <div>                        
                        Поделиться статьей:
                        <script type="text/javascript" src="//yandex.st/share/share.js" charset="utf-8"></script>
                        <div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="none" data-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir,lj,friendfeed,moikrug"></div> 
                    </div>
                </div>

              

            </div>
        </div>


 <div id="main_block">
            <div class="container">
                <div id="main_content">
 

                    <div id="description" class="content">
                        <!-- google_ad_section_start -->
                        <?php echo $this->event->getContent(array("\n" => '</p><p>')); ?>
                        <!-- google_ad_section_end -->
                    </div>
                    <div>
                        <?php echo $this->partial(
                                'calendar/elements/social_plugin.phtml',
                                array(
                                    'pageId'=> $this->event->getId(),
                                    'url' => $this->event->getLink(),
                                
                                )); ?>
                    </div>
                    
                    
                </div>

            <div id="add_content">
                 <?php if ($this->icons): ?>
                 <h4> 
                    Иконы к событию 
                    <strong>"<?php echo $this->event->getTitle();?>"</strong>
                 </h4>
                 <div id="icons">
                    <?php foreach ($this->icons as $icon): ?>
                    <div class='icon'>
                    <a href='<?php echo str_replace(
                                  '*size*', '450x600', 
                                  $icon->url
                             );?>'
                      rel="lightbox[icons]"
                      title='<?php echo $icon->text->title;?>'
                    >
                    <img
                      src='<?php echo str_replace('*size*', '75x100', $icon->url);?>'
                      title='<?php echo $icon->text->title;?>'
                      alt='<?php echo $icon->text->annonce;?>'>
                     </a>
                    </div>
                  <?php endforeach;?>
                </div>
              <?php endif;?>

                <?php if ($this->event->getId() !=  Config_Interface::get('everyWeekFast', 'events')):?>
                <div id="event_in_future">
                   
                    <h4><strong><?php echo $this->event->getTitle();?></strong> в будущем году</h4>
                    
                    <div id="dates">                        
                        <?php echo $this->EventInFuture($this->event, $this->date);?>                             
                    </div>
                </div>
                <?php endif;?>

                <?php if ($this->articles->getCount() > 0): ?>
               
                <div id="articles">
                    <h4>Что еще можно прочесть по теме <strong>"<?php echo $this->event->getTitle();?>"</strong>:</h4>
                   
                         

                             <?php foreach ($this->articles as $article): ?>
                                 <p><?php echo $article->getLink($article->getTitle(), array(
                                     'event_id' => $this->event->getId()
                                 ));?></p>
                             <?php endforeach;?>
                         
                </div>
                <?php endif; ?>
                <?php echo $this->partial('calendar/elements/adSense.phtml'); ?>
            </div>
        </div>
        </div>

<?php echo $this->partial('calendar/elements/footer.phtml',array(
                            'data' => $this->date,
                            'nextEvents' => $this->nextEvents,
                            'prevEvents' => $this->prevEvents
                         ));
?>

<?php echo $this->partial('calendar/elements/copyright.phtml');?>     

<script>
    $("#to_future_show").click(function () {
       if ($("#otherDates").is(":hidden")) {
           $("#otherDates").show("slow");
       } else {
           $("#otherDates").hide("slow");
       }
    });
</script>
