<style>
    ul li {list-style-type: none;}
</style>
<div>
    <ul>
        <li>
            <a  href="javascript::void(0)" class="category_active"> Категории</a>
            <a href="/calendar/category-create/id/<?php echo $this->categoryId ?>/">
                <?php echo $this->iconOutput('create'); ?>
            </a>
            <?php echo $this->treeMenuOutput($this->categoryes, $this->categoryId) ?>
            
    </li>
</ul>
</div>

