<!DOCTYPE html
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <!-- Framework CSS -->
        <link rel="stylesheet" href="/css/blueprint/screen.css" type="text/css" media="screen, projection">
        <link rel="stylesheet" href="/css/blueprint/print.css" type="text/css" media="print">
        <!--[if lt IE 8]>
            <link rel="stylesheet" href="/css/blueprint/ie.css" type="text/css" media="screen, projection">
        <![endif]-->
        <link rel="stylesheet" href="/css/blueprint/plugins/fancy-type/screen.css" type="text/css" media="screen, projection">
        <link rel="stylesheet" href="/css/blueprint/plugins/buttons/screen.css" type="text/css" media="screen, projection">

        <?= $this->headTitle() ?>
        <?= $this->headScript() ?>
        <?= $this->headLink() ?>
    </head>
    <body>
        <div class="container">
            <div class="span-4 border">
                <a href="/calendar/category-list/">Категории (read only)</a> <br/>
                <a href="/calendar/category-list/id/1">Православие</a><br/>
                <a href="/article/list">Статьи</a><br/>
                <a href="/template/list">Шаблоны</a><br/>
                <a href="/icon/list">Иконы</a><br/>                
            </div>
            <div class="span-20 last">
                    <?= $this->layout()->content ?>
            </div>
            <hr/>
                <a href="/index/clearcache">Сбросить кеша</a>
        </div>
    </body>
</html>