<form
    action="<?= $this->escape($this->element->getAction());  ?>"
    method="<?= $this->escape($this->element->getMethod());  ?>">
    <div class="form_element clearfix">
        <div class="element">
            <?php echo $this->element->email; ?>
        </div>
        <div class="information clearfix">
            На указанный при регистрации адрес электронной почты будут высланы инструкции по восстановлению пароля
        </div>
    </div>

     <div class="form_element clearfix">
        <div class="element">
             <?php echo $this->element->done; ?>
        </div>
        <div class="information clearfix">

        </div>
    </div>

</form>