<?php echo $this->partial('calendar/elements/header_menu.phtml'); ?>
<?php echo $this->partial('calendar/elements/month_menu.phtml', array('data' => $this->date));?>

   
<div id="main_block">
    <div class="container">
        <div class="form">
            <?php if ($this->successText):?>
                <div class="success">
                    <?php echo $this->successText;?>
                </div>
            <?php endif; ?>
            <h1>Обратная связь с администрацией проекта.</h1>
            <?php echo $this->form;?>
     
        </div>
    </div> 
</div>
      
<?php echo $this->partial('calendar/elements/footer.phtml',array(  
    'data' => $this->date,   
    'nextEvents' => $this->nextEvents,
    'prevEvents' => $this->prevEvents
)); ?>           
 
<?php echo $this->partial('calendar/elements/copyright.phtml');?>               
