<?php echo $this->partial('calendar/elements/header_menu.phtml'); ?>
<?php echo $this->partial('calendar/elements/month_menu.phtml',
                          array(
                              'data' => $this->date
                          ));
?>
 <div id="page">
    <div class="container">
        <div id="content">
              <b>Спасибо!</b> Ваш платеж поможет развитию проекта
        </div>
    </div>
 </div>


 

<?php echo $this->partial('calendar/elements/footer.phtml',array(
                            'data' => $this->date,
                            'nextEvents' => $this->nextEvents,
                            'prevEvents' => $this->prevEvents
                         ));
?>

<?php echo $this->partial('calendar/elements/copyright.phtml');?>
