<div id="adSense">
    <!-- Яндекс.Директ -->
    <script type="text/javascript">
    //<![CDATA[
        yandex_partner_id = 84165;
        yandex_site_bg_color = 'FFFFFF';
        yandex_site_charset = 'utf-8';
        yandex_ad_format = 'direct';
        yandex_font_size = 0.9;
        yandex_direct_type = 'vertical';
        yandex_direct_limit = 5;
        yandex_direct_title_font_size = 1;
        yandex_direct_header_bg_color = 'FEEAC7';
        yandex_direct_title_color = 'AB8000';
        yandex_direct_url_color = '000000';
        yandex_direct_all_color = '000000';
        yandex_direct_text_color = '666666';
        yandex_direct_hover_color = '000000';
        yandex_direct_favicon = false;
        document.write('<sc'+'ript type="text/javascript" src="http://an.yandex.ru/system/context.js"></sc'+'ript>');
        //]]>
    </script>
</div>
<hr/>
<a href="http://top777.ariom.ru/">
    <img src="http://top777.ariom.ru/button.php?u=ravall" alt="ТОП-777: рейтинг сайтов, развивающих Человека" width="88" height="31" border="0" />
</a>

<!--begin of Hristianstvo.Ru-->
<a href="http://www.hristianstvo.ru/?from=15950"><img
src="http://www.hristianstvo.ru/images/ru-88x31-native1.gif"
title="Православное христианство" width=88 height=31 border=0></a>
<!--end of Hristianstvo.Ru-->


<!-- Top SunHome.ru counter -->
<script type="text/javascript">
var referer = (document.referrer != undefined) ? escape(document.referrer) : '';
var script = 'http://www.sunhome.ru/counter.php';
var q = '?id=10159&c=2' 
+ '&uri=' + escape(document.URL)
+ '&referer=' + referer
+ '&rand=' + Math.random();
document.write('<a href="http://www.sunhome.ru/" target="_blank" title="Рейтинг сайтов SunHome.ru (Дом Солнца)">' 
    + '<img src="' + script + q + '" border="0" width="88" height="31" alt="Рейтинг сайтов SunHome.ru (Дом Солнца)">'
    + '</a>');
</script>
<noscript><a href="http://www.sunhome.ru/" title="Рейтинг сайтов SunHome.ru (Дом Солнца)" target="_blank"><img src="http://www.sunhome.ru/counter.php?id=10159&c=2" border="0" width="88" height="31" alt="Рейтинг сайтов SunHome.ru (Дом Солнца)"></a></noscript>
<!-- End Top SunHome.ru counter -->