<h2><?php echo ($this->data->isToday() ? 'Сегодня ' : '') . $this->data->getFormatDay() ?></h2>

<div class="note">
    <?=($this->notes)?('В этот день: '.implode(', ', $this->notes)):'';?>
</div>


<?php if ($this->events->getCount()):?>
<div id="events">
  События дня: <?php echo implode(', ', $this->events->getLinkArray())?><?php if ($this->informationEvents->getCount()):?>,
  а так же
  <?php echo implode(', ', $this->informationEvents->getLinkArray())?>
</div>
<?php endif;?>


<?php elseif ($this->informationEvents->getCount()):?>
<div id="events">
  События дня:  <?php echo implode(', ', $this->informationEvents->getLinkArray())?>
</div>
<?php endif;?>


<?php if ($this->saintDayEvent->getCount()):?>
<div id="saint">
  Святые, почитаемые в этот день: <?php echo implode(', ', $this->saintDayEvent->getLinkArray())?>
</div>
<?php endif;?>

<?php if ($this->articlesForEveryDay->getCount()):?>
<div id="articles">
  Заметки православному на каждый день: <?php echo implode(', ', $this->articlesForEveryDay->getLinkArray())?>
</div>
<?php endif;?>

<div id='icons_day' class='clearfix'>
    <?php $count=0;?>
 	  <?php if (count($this->icons)):?>
 		    <h3>Иконы дня</h3>
        <?php foreach ($this->icons as $icon): ?>
            <?php if ($count >0 && $count % 3 == 0): ?>
              </div>
              <div id='icons_day' class='clearfix'>
            <?php endif;?>
    	      <div class='icon'>
    	          <a
                  href='http://img.sancta.ru/crop/450x600/<?php echo $icon->image;?>'
                  rel="lightbox[icons]"
                  title='<?php echo $icon->text->annonce;?>'
                >

                    <img
                      src='http://img.sancta.ru/crop/150x200/<?php echo $icon->image;?>'
    		              title='<?php echo $icon->text->title;?>'
    		              alt='<?php echo $icon->text->annonce;?>'>
                </a><br/>
                <div class='desc'><?php echo $icon->text->annonce;?></div>
    	      </div>
        <?php $count++?>
        <?php endforeach;?>

    <?php endif;?>
</div>




