<h2><?php echo ($this->data->isToday() ? 'Сегодня ' : '') . $this->data->getFormatDay() ?></h2>

<div class="note">
    <?=($this->notes)?('В этот день: '.implode(', ', $this->notes)):'';?>
</div>


<?php if ($this->events->getCount()):?>
<div id="events">
  События дня: <?php echo implode(', ', $this->events->getLinkArray())?><?php if ($this->informationEvents->getCount()):?>,
  а так же
  <?php echo implode(', ', $this->informationEvents->getLinkArray())?>
</div>
<?php endif;?>


<?php elseif ($this->informationEvents->getCount()):?>
<div id="events">
  События дня:  <?php echo implode(', ', $this->informationEvents->getLinkArray())?>
</div>
<?php endif;?>


<?php if ($this->saintDayEvent->getCount()):?>
<div id="saint">
  Святые, почитаемые в этот день: <?php echo implode(', ', $this->saintDayEvent->getLinkArray())?>
</div>
<?php endif;?>

<?php if ($this->articlesForEveryDay->getCount()):?>
<div id="articles">
  Заметки православному на каждый день: <?php echo implode(', ', $this->articlesForEveryDay->getLinkArray())?>
</div>
<?php endif;?>

<div id='icons_day' class='clearfix'>
 	  <?php if ($this->icons['count']):?>
 		    <h3>Иконы дня</h3>
        <?php foreach ($this->icons['row'] as $icon): ?>
    	      <div class='icon'>
    	          <a
                  href='<?php echo str_replace('*size*', '450x600', $icon->url);?>'
                  rel="lightbox[icons]"
                  title='<?php echo $icon->text->annonce;?>'
                >

                    <img
    		              src='<?php echo str_replace('*size*', '150x200', $icon->url);?>'
    		              title='<?php echo $icon->text->title;?>'
    		              alt='<?php echo $icon->text->annonce;?>'>
                </a><br/>
                <div class='desc'><?php echo $icon->text->annonce;?></div>
    	      </div>

        <?php endforeach;?>

    <?php endif;?>
</div>
<?php if ($this->icons['count'] > 3):?>
          <a href='<?=$this->url(array('date'=>$this->data->getDay()), 'orthodoxyicons')?>'>
              посмотреть все иконы дня на <?php echo $this->data->getFormatDay()?>
          </a>
<?php endif;?>





