<h2><?php echo ($this->data->isToday() ? 'Сегодня ' : '') . $this->data->getFormatDay() ?></h2>

<div class="note">
    <?=($this->notes)?('В этот день: '.implode(', ', $this->notes)):'';?>
</div>


<?php if ($this->events->getCount()):?>
<div id="events">
  События дня: <?php echo implode(', ', $this->events->getLinkArray())?><?php if ($this->informationEvents->getCount()):?>,
  а так же
  <?php echo implode(', ', $this->informationEvents->getLinkArray())?>
</div>
<?php endif;?>


<?php elseif ($this->informationEvents->getCount()):?>
<div id="events">
  События дня:  <?php echo implode(', ', $this->informationEvents->getLinkArray())?>
</div>
<?php endif;?>


<?php if ($this->saintDayEvent->getCount()):?>
<div id="saint">
  Святые, почитаемые в этот день: <?php echo implode(', ', $this->saintDayEvent->getLinkArray())?>
</div>
<?php endif;?>

<?php if ($this->articlesForEveryDay->getCount()):?>
<div id="articles">
  Заметки православному на каждый день: <?php echo implode(', ', $this->articlesForEveryDay->getLinkArray())?>
</div>
<?php endif;?>

 <div id='icons_day' class='clearfix'>
 	<?php if (!empty($this->icons)):?>
 		<h3>Иконы дня</h3>

    <?php 
    	$count=0;
    	foreach ($this->icons as $icon): ?> 
    	<?php 
       if ($count++==3) {
    		break;
    	}?>
    	<div class='icon'>
    	<img 
    		src='<?php echo $icon->urls->{'150x200'};?>'
    		title='<?php echo $icon->text->title;?>'
    		alt='<?php echo $icon->text->annonce;?>'
    	><br/>
    	<span class='desc'><?php echo $icon->text->annonce;?></span>
    	</div>
    <?php endforeach;?>
    <?php if ($this->iconsCount > 3):?>
      <a href='#'>посмотреть другие <?php echo $this->iconsCount;?> икон дня</a>
    <?php endif;?>
    <?php endif;?>
</div>


        


