<div id="header_menu">
    <div class="navigation">
        <ul class="sitemenu">
            <li id="home">
                <a href="<?=$this->url(array('date' => $this->TodayDate()),'orthodoxy')?>" title="православный календарь на сегодня"></a>
            </li>
            <li id="rss">
                <a href="<?=$this->url(array(),'rss')?>" title="православный календарь в rss ленте"></a>
            </li>
        </ul>
        <ul class="usermenu">
            <li>
                <a
                href="<?=$this->url(array('date' => $this->TodayDate()),'orthodoxy')?>" title="православный календарь на сегодня">Сегодня</a>
            </li>
        </ul>
    </div>
</div>