<div id="month_menu">            
    <div class="navigation">
    <ul>
        <li <?=$this->data->getM()==1?"class='active'":"";?>><a  href="<?=$this->url(array('date' => $this->data->getY().'-01-01'), 'orthodoxy')?>" title="календарь на январь">Январь</a></li>
        <li <?=$this->data->getM()==2?"class='active'":"";?>><a  href="<?=$this->url(array('date' => $this->data->getY().'-02-01'), 'orthodoxy')?>" title="календарь на февраль">Февраль</a></li>
        <li <?=$this->data->getM()==3?"class='active'":"";?>><a  href="<?=$this->url(array('date' => $this->data->getY().'-03-01'), 'orthodoxy')?>" title="календарь на март">Март</a></li>
        <li <?=$this->data->getM()==4?"class='active'":"";?>><a  href="<?=$this->url(array('date' => $this->data->getY().'-04-01'), 'orthodoxy')?>" title="календарь на апрель">Апрель</a></li>
        <li <?=$this->data->getM()==5?"class='active'":"";?>><a  href="<?=$this->url(array('date' => $this->data->getY().'-05-01'), 'orthodoxy')?>" title="календарь на май">Май</a></li>
        <li <?=$this->data->getM()==6?"class='active'":"";?>><a  href="<?=$this->url(array('date' => $this->data->getY().'-06-01'), 'orthodoxy')?>" title="календарь на июнь">Июнь</a></li>
        <li <?=$this->data->getM()==7?"class='active'":"";?>><a  href="<?=$this->url(array('date' => $this->data->getY().'-07-01'), 'orthodoxy')?>" title="календарь на июль">Июль</a></li>
        <li <?=$this->data->getM()==8?"class='active'":"";?>><a  href="<?=$this->url(array('date' => $this->data->getY().'-08-01'), 'orthodoxy')?>" title="календарь на август">Август</a></li>
        <li <?=$this->data->getM()==9?"class='active'":"";?>><a  href="<?=$this->url(array('date' => $this->data->getY().'-09-01'), 'orthodoxy')?>" title="календарь на сентябрь">Сентябрь</a></li>
        <li <?=$this->data->getM()==10?"class='active'":"";?>><a href="<?=$this->url(array('date' => $this->data->getY().'-10-01'), 'orthodoxy')?>" title="календарь на октябрь">Октябрь</a></li>
        <li <?=$this->data->getM()==11?"class='active'":"";?>><a href="<?=$this->url(array('date' => $this->data->getY().'-11-01'), 'orthodoxy')?>" title="календарь на ноябрь">Ноябрь</a></li>
        <li <?=$this->data->getM()==12?"class='active'":"";?>><a href="<?=$this->url(array('date' => $this->data->getY().'-12-01'), 'orthodoxy')?>" title="календарь на декабрь">Декабрь</a></li>                
    </ul>            
    </div>
</div>