<hr/>
<table>
    <tr>
        
     <td width="150px"> 
<div id="vk_like"></div>
<script type="text/javascript">
VK.Widgets.Like("vk_like", {type: "button", verb: 1},<?=$this->pageId?>);
</script>
     </td>
     <td  width="150px">
<a class="odkl-klass-stat" href="<?=$this->url?>" onclick="ODKL.Share(this);return false;" ><span>0</span></a>
     </td>
     
     <td width="150px">
         <div class="fb-like" data-send="false" data-layout="button_count" data-width="100" data-show-faces="false" data-action="recommend" data-font="verdana"></div>
     </td>
</tr>
</table>