 <div id="event_page" class="container">
         <div class="span-8 border">
             <?php echo $this->partial(
                     'index/elements/links.phtml', array(
                         'links' => $this->links,                         
                    ));
             ?>
         </div>
         <div class="span-15 prepend-1 last text_content">
             <h2 class="alt">Календарь</h2>
             <h1>О проекте</h1>
             <p>&nbsp;</p>
             <p><?php  echo Calendar_Template::getByName('about_project',array("\n" => '</p><p>')); ?></p>
         </div>

        <div id ="footer" class="span-24 last">
            <hr class="prepend-1 append-1"/>
                 <?php echo $this->partial('index/elements/footer.phtml'); ?>
        </div>
    </div>