<!DOCTYPE html
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
     
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name='yandex-verification' content='7724c57bbe842f08' /> 
     
        <?php echo $this->headMeta() ?>
        <link rel="icon" type="image/x-icon" href="/images/favicon.ico" />
        <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">

        <link rel="stylesheet" href="/css/screen.css" type="text/css" media="screen, projection"/>   
        <link rel="alternate" type="application/rss+xml" title="Лента событий православного календаря" href="<?=$this->url(array(),'rss')?>" />
        <meta property="vk:app_id" content="2793550" />
        <?php echo $this->headTitle() ?>
        <?php echo $this->headScript(); ?>
        <?php echo $this->headLink(); ?>
        
        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-21317987-2']);
            _gaq.push(['_trackPageview']);
            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>
        
        
        <script src="http://vkontakte.ru/js/api/openapi.js" type="text/javascript" charset="windows-1251"></script>
        <link href="http://stg.odnoklassniki.ru/share/odkl_share.css" rel="stylesheet"/>
        <script src="http://stg.odnoklassniki.ru/share/odkl_share.js" type="text/javascript" ></script>
    </head>
    <body onload="ODKL.init();">
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = "//connect.facebook.net/ru_RU/all.js#xfbml=1";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
        </script>
        
        <?php  echo $this->layout()->content; ?>

   <!-- Yandex.Metrika counter --><script type="text/javascript">(function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter4393480 = new Ya.Metrika({id:4393480, enableAll: true, webvisor:true}); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="//mc.yandex.ru/watch/4393480" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->
    
    <!-- счетчик http://poisk.cerkov.ru -->
    <script type="text/javascript" src="http://poisk.cerkov.ru/res/public/php/counter.php?id=3352"></script>
    <!-- end -->
    </body>
        
</html>
