<?php echo $this->partial('calendar/elements/header_menu.phtml'); ?>
<?php echo $this->partial('calendar/elements/month_menu.phtml',
                          array(
                              'data' => $this->date
                          ));
?>



<div id="icons_card" class="clearfix">
            <div class="container">
                <div id="card" class="clearfix">
                    <h1>Иконы дня на <?php echo $this->date->getFormatDay()?></h1>
                    <h2>Православный календарь</h2>
                    <a href="<?=$this->url(array('date'=>$this->date->getDay()), 'orthodoxy')?>"> &larr; к странице календаря</a>
                </div>
            </div>
        </div>



<div id="main_block" class='icons'>
    <div class="container">
        <div id="main_content">





    <?php if ($this->icons['count']):?>

        <?php $count = 0;?>
        <div id='icons_day' class='clearfix'>
        <?php foreach ($this->icons['all'] as $icon): ?>
            <?php if ($count >0 && $count % 3 == 0): ?>
              </div>
              <div id='icons_day' class='clearfix'>
            <?php endif;?>
            <div class='icon'>
                 <a
                  href='<?php echo str_replace('*size*', '450x600', $icon->url);?>'
                  rel="lightbox[allicons]"
                  title='<?php echo $icon->text->annonce;?>'
                >
                  <img
                    src='<?php echo str_replace('*size*', '150x200', $icon->url);?>'
                    title='<?php echo $icon->text->title;?>'
                    alt='<?php echo $icon->text->annonce;?>'>
                </a><br/>
                <div class='desc'><?php echo $icon->text->annonce;?></div>
            </div>

        <?php $count++;?>
        <?php endforeach;?>
        </div>

    <?php endif;?>

        </div>
        <div id="add_content">
            <div id="articles">
                <h4>Что еще можно прочесть по теме:</h4>
                <?php foreach ($this->articles as $article): ?>
                    <p><?php echo $article->getLink($article->getTitle());?></p>
                <?php endforeach;?>
            </div>
            <?php echo $this->partial('calendar/elements/adSense.phtml'); ?>
        </div>
    </div>
</div>




<?php echo $this->partial('calendar/elements/footer.phtml',array(
                            'data' => $this->date,
                            'nextEvents' => $this->nextEvents,
                            'prevEvents' => $this->prevEvents
                         ));
?>

<?php echo $this->partial('calendar/elements/copyright.phtml');?>
